angular.module("components",[
	"register",
	'signUpForm',
	'headerBar',
	'signInForm',
	'createGameForm',
	'teamCreateForm',
	'selectPlayers',
	'teamList',
	'teamPlayerList',
	'createTournament',
	'createMatchForm',
	'tournamentsList',
	'matchView',
	'fixtures',
	'viewTeams'
	]);